import React from "react";
import styles from './Ciudades.module.css';

const Ciudades = () => (
    <aside className={styles.ciudades}>
        <div class="card text-light bg-dark m-5">
            <div class="card-body">
                <h3 class="card-title mb-4">Ciudades disponibles</h3>
                <div className={styles.lista}>
                    <ul>
                        <li class="list-unstyled ">	Aberdeen	</li>
                        <li class="list-unstyled">	Abidjan	</li>
                        <li class="list-unstyled">	Addis Ababa	</li>
                        <li class="list-unstyled">	Adelaide	</li>
                        <li class="list-unstyled">	Ahmedabad	</li>
                        <li class="list-unstyled">	Ajaccio	</li>
                        <li class="list-unstyled">	Albuquerque	</li>
                        <li class="list-unstyled">	Alexandria	</li>
                        <li class="list-unstyled">	Amsterdam	</li>
                        <li class="list-unstyled">	Anchorage	</li>
                        <li class="list-unstyled">	Ankara	</li>
                        <li class="list-unstyled">	Athens	</li>
                        <li class="list-unstyled">	Atlanta	</li>
                        <li class="list-unstyled">	Auckland	</li>
                        <li class="list-unstyled">	Austin	</li>
                        <li class="list-unstyled">	Baghdad	</li>
                        <li class="list-unstyled">	Bakersfield	</li>
                        <li class="list-unstyled">	Baltimore	</li>
                        <li class="list-unstyled">	Bangalore	</li>
                        <li class="list-unstyled">	Bangkok	</li>
                        <li class="list-unstyled">	Barcelona	</li>
                        <li class="list-unstyled">	Beijing	</li>
                        <li class="list-unstyled">	Belfast	</li>
                        <li class="list-unstyled">	Berlin	</li>
                        <li class="list-unstyled">	Billings	</li>
                        <li class="list-unstyled">	Birmingham	</li>
                        <li class="list-unstyled">	Birmingham	</li>
                        <li class="list-unstyled">	Blackpool	</li>
                        <li class="list-unstyled">	Bogotá	</li>
                        <li class="list-unstyled">	Boise	</li>
                        <li class="list-unstyled">	Bordeaux	</li>
                        <li class="list-unstyled">	Boston	</li>
                        <li class="list-unstyled">	Boulder	</li>
                        <li class="list-unstyled">	Bournemouth	</li>
                        <li class="list-unstyled">	Bradford	</li>
                        <li class="list-unstyled">	Brasília	</li>
                        <li class="list-unstyled">	Bremen	</li>
                        <li class="list-unstyled">	Bridgeport	</li>
                        <li class="list-unstyled">	Brighton	</li>
                        <li class="list-unstyled">	Brisbane	</li>
                        <li class="list-unstyled">	Bristol	</li>
                        <li class="list-unstyled">	Brussels	</li>
                        <li class="list-unstyled">	Bucharest	</li>
                        <li class="list-unstyled">	Budapest	</li>
                        <li class="list-unstyled">	Buenos Aires	</li>
                        <li class="list-unstyled">	Burlington	</li>
                        <li class="list-unstyled">	Busan	</li>
                        <li class="list-unstyled">	Cairo	</li>
                        <li class="list-unstyled">	Calgary	</li>
                        <li class="list-unstyled">	Calvi	</li>
                        <li class="list-unstyled">	Cambridge	</li>
                        <li class="list-unstyled">	Cape Town	</li>
                        <li class="list-unstyled">	Caracas	</li>
                        <li class="list-unstyled">	Cardiff	</li>
                        <li class="list-unstyled">	Casablanca	</li>
                        <li class="list-unstyled">	Charleston	</li>
                        <li class="list-unstyled">	Charlotte	</li>
                        <li class="list-unstyled">	Chengdu	</li>
                        <li class="list-unstyled">	Chennai	</li>
                        <li class="list-unstyled">	Cheyenne	</li>
                        <li class="list-unstyled">	Chicago	</li>
                        <li class="list-unstyled">	Christchurch	</li>
                        <li class="list-unstyled">	Cologne	</li>
                        <li class="list-unstyled">	Colorado Springs	</li>
                        <li class="list-unstyled">	Columbia	</li>
                        <li class="list-unstyled">	Columbus	</li>
                        <li class="list-unstyled">	Copenhagen	</li>
                        <li class="list-unstyled">	Coventry	</li>
                        <li class="list-unstyled">	Dallas	</li>
                        <li class="list-unstyled">	Damascus	</li>
                        <li class="list-unstyled">	Denpasar	</li>
                        <li class="list-unstyled">	Denver	</li>
                        <li class="list-unstyled">	Derby	</li>
                        <li class="list-unstyled">	Des Moines	</li>
                        <li class="list-unstyled">	Detroit	</li>
                        <li class="list-unstyled">	Dhaka	</li>
                        <li class="list-unstyled">	Dongguan	</li>
                        <li class="list-unstyled">	Dortmund	</li>
                        <li class="list-unstyled">	Dresden	</li>
                        <li class="list-unstyled">	Dubai	</li>
                        <li class="list-unstyled">	Dublin	</li>
                        <li class="list-unstyled">	Dundee	</li>
                        <li class="list-unstyled">	Durban	</li>
                        <li class="list-unstyled">	Düsseldorf	</li>
                        <li class="list-unstyled">	Edinburgh	</li>
                        <li class="list-unstyled">	Edmonton	</li>
                        <li class="list-unstyled">	El Paso	</li>
                        <li class="list-unstyled">	Essen	</li>
                        <li class="list-unstyled">	Exeter	</li>
                        <li class="list-unstyled">	Falmouth	</li>
                        <li class="list-unstyled">	Fargo	</li>
                        <li class="list-unstyled">	Fort Worth	</li>
                        <li class="list-unstyled">	Frankfurt	</li>
                        <li class="list-unstyled">	Fresno	</li>
                        <li class="list-unstyled">	Fukuoka	</li>
                        <li class="list-unstyled">	Geneva	</li>
                        <li class="list-unstyled">	Glasgow	</li>
                        <li class="list-unstyled">	Gothenburg	</li>
                        <li class="list-unstyled">	Guangzhou	</li>
                        <li class="list-unstyled">	Hà Nội	</li>
                        <li class="list-unstyled">	Hamburg	</li>
                        <li class="list-unstyled">	Hangzhou	</li>
                        <li class="list-unstyled">	Hanover	</li>
                        <li class="list-unstyled">	Helsinki	</li>
                        <li class="list-unstyled">	Hiroshima	</li>
                        <li class="list-unstyled">	Ho Chi Minh City	</li>
                        <li class="list-unstyled">	Hong Kong	</li>
                        <li class="list-unstyled">	Honolulu	</li>
                        <li class="list-unstyled">	Houston	</li>
                        <li class="list-unstyled">	Huddersfield	</li>
                        <li class="list-unstyled">	Hyderabad	</li>
                        <li class="list-unstyled">	Ibadan	</li>
                        <li class="list-unstyled">	Indianapolis	</li>
                        <li class="list-unstyled">	Ipswich	</li>
                        <li class="list-unstyled">	Istanbul	</li>
                        <li class="list-unstyled">	İzmir	</li>
                        <li class="list-unstyled">	Jackson	</li>
                        <li class="list-unstyled">	Jacksonville	</li>
                        <li class="list-unstyled">	Jakarta	</li>
                        <li class="list-unstyled">	Johannesburg	</li>
                        <li class="list-unstyled">	Kano	</li>
                        <li class="list-unstyled">	Kansas City	</li>
                        <li class="list-unstyled">	Karachi	</li>
                        <li class="list-unstyled">	Kawasaki	</li>
                        <li class="list-unstyled">	Kharkiv	</li>
                        <li class="list-unstyled">	Kiev	</li>
                        <li class="list-unstyled">	Kingston upon Hull	</li>
                        <li class="list-unstyled">	Kinshasa	</li>
                        <li class="list-unstyled">	Kirkwall	</li>
                        <li class="list-unstyled">	Kitakyushu	</li>
                        <li class="list-unstyled">	Kobe	</li>
                        <li class="list-unstyled">	Kolkata	</li>
                        <li class="list-unstyled">	Kuala Lumpur	</li>
                        <li class="list-unstyled">	Kyoto	</li>
                        <li class="list-unstyled">	Lagos	</li>
                        <li class="list-unstyled">	Lahore	</li>
                        <li class="list-unstyled">	Lake Tahoe	</li>
                        <li class="list-unstyled">	Las Vegas	</li>
                        <li class="list-unstyled">	Leeds	</li>
                        <li class="list-unstyled">	Leicester	</li>
                        <li class="list-unstyled">	Leipzig	</li>
                        <li class="list-unstyled">	Lille	</li>
                        <li class="list-unstyled">	Lima	</li>
                        <li class="list-unstyled">	Lisbon	</li>
                        <li class="list-unstyled">	Little Rock	</li>
                        <li class="list-unstyled">	Liverpool	</li>
                        <li class="list-unstyled">	London	</li>
                        <li class="list-unstyled">	Long Beach	</li>
                        <li class="list-unstyled">	Los Angeles	</li>
                        <li class="list-unstyled">	Louisville	</li>
                        <li class="list-unstyled">	Luton	</li>
                        <li class="list-unstyled">	Lyon	</li>
                        <li class="list-unstyled">	Madrid	</li>
                        <li class="list-unstyled">	Manchester	</li>
                        <li class="list-unstyled">	Manchester	</li>
                        <li class="list-unstyled">	Manila	</li>
                        <li class="list-unstyled">	Manukau	</li>
                        <li class="list-unstyled">	Maracaibo	</li>
                        <li class="list-unstyled">	Marseille	</li>
                        <li class="list-unstyled">	Melbourne	</li>
                        <li class="list-unstyled">	Memphis	</li>
                        <li class="list-unstyled">	Mesa	</li>
                        <li class="list-unstyled">	Mexico City	</li>
                        <li class="list-unstyled">	Miami	</li>
                        <li class="list-unstyled">	Middlesbrough	</li>
                        <li class="list-unstyled">	Milan	</li>
                        <li class="list-unstyled">	Milwaukee	</li>
                        <li class="list-unstyled">	Minneapolis	</li>
                        <li class="list-unstyled">	Minsk	</li>
                        <li class="list-unstyled">	Mombasa	</li>
                        <li class="list-unstyled">	Montréal	</li>
                        <li class="list-unstyled">	Moscow	</li>
                        <li class="list-unstyled">	Mountain View	</li>
                        <li class="list-unstyled">	Mumbai	</li>
                        <li class="list-unstyled">	Munich	</li>
                        <li class="list-unstyled">	Nagoya	</li>
                        <li class="list-unstyled">	Nairobi	</li>
                        <li class="list-unstyled">	Naples	</li>
                        <li class="list-unstyled">	Nashville	</li>
                        <li class="list-unstyled">	New Delhi	</li>
                        <li class="list-unstyled">	New Orleans	</li>
                        <li class="list-unstyled">	New York	</li>
                        <li class="list-unstyled">	Newark	</li>
                        <li class="list-unstyled">	Newcastle	</li>
                        <li class="list-unstyled">	Nice	</li>
                        <li class="list-unstyled">	Northampton	</li>
                        <li class="list-unstyled">	Norwich	</li>
                        <li class="list-unstyled">	Nottingham	</li>
                        <li class="list-unstyled">	Nuremberg	</li>
                        <li class="list-unstyled">	Oakland	</li>
                        <li class="list-unstyled">	Oklahoma City	</li>
                        <li class="list-unstyled">	Omaha	</li>
                        <li class="list-unstyled">	Osaka	</li>
                        <li class="list-unstyled">	Oslo	</li>
                        <li class="list-unstyled">	Oxford	</li>
                        <li class="list-unstyled">	Palm Springs	</li>
                        <li class="list-unstyled">	Paris	</li>
                        <li class="list-unstyled">	Penzance	</li>
                        <li class="list-unstyled">	Perth	</li>
                        <li class="list-unstyled">	Philadelphia	</li>
                        <li class="list-unstyled">	Phoenix	</li>
                        <li class="list-unstyled">	Phuket	</li>
                        <li class="list-unstyled">	Plymouth	</li>
                        <li class="list-unstyled">	Portland	</li>
                        <li class="list-unstyled">	Portland	</li>
                        <li class="list-unstyled">	Portsmouth	</li>
                        <li class="list-unstyled">	Prague	</li>
                        <li class="list-unstyled">	Preston	</li>
                        <li class="list-unstyled">	Providence	</li>
                        <li class="list-unstyled">	Pune	</li>
                        <li class="list-unstyled">	Pyongyang	</li>
                        <li class="list-unstyled">	Raleigh	</li>
                        <li class="list-unstyled">	Reading	</li>
                        <li class="list-unstyled">	Rhyl	</li>
                        <li class="list-unstyled">	Richmond	</li>
                        <li class="list-unstyled">	Rio de Janeiro	</li>
                        <li class="list-unstyled">	Riyadh	</li>
                        <li class="list-unstyled">	Rome	</li>
                        <li class="list-unstyled">	Sacramento	</li>
                        <li class="list-unstyled">	Saitama	</li>
                        <li class="list-unstyled">	Salford	</li>
                        <li class="list-unstyled">	Salt Lake City	</li>
                        <li class="list-unstyled">	Salvador	</li>
                        <li class="list-unstyled">	San Antonio	</li>
                        <li class="list-unstyled">	San Diego	</li>
                        <li class="list-unstyled">	San Francisco	</li>
                        <li class="list-unstyled">	San Jose	</li>
                        <li class="list-unstyled">	Santa Cruz	</li>
                        <li class="list-unstyled">	Santa Cruz de Tenerife	</li>
                        <li class="list-unstyled">	Santa Fe	</li>
                        <li class="list-unstyled">	Santander	</li>
                        <li class="list-unstyled">	Santiago	</li>
                        <li class="list-unstyled">	Santorini	</li>
                        <li class="list-unstyled">	São Paulo	</li>
                        <li class="list-unstyled">	Sapporo	</li>
                        <li class="list-unstyled">	Seattle	</li>
                        <li class="list-unstyled">	Sendai	</li>
                        <li class="list-unstyled">	Seoul	</li>
                        <li class="list-unstyled">	Shanghai	</li>
                        <li class="list-unstyled">	Sheffield	</li>
                        <li class="list-unstyled">	Shenzhen	</li>
                        <li class="list-unstyled">	Sidmouth	</li>
                        <li class="list-unstyled">	Singapore	</li>
                        <li class="list-unstyled">	Sioux Falls	</li>
                        <li class="list-unstyled">	Sofia	</li>
                        <li class="list-unstyled">	Southend-on-Sea	</li>
                        <li class="list-unstyled">	St Ives	</li>
                        <li class="list-unstyled">	St Petersburg	</li>
                        <li class="list-unstyled">	St. Louis	</li>
                        <li class="list-unstyled">	Stockholm	</li>
                        <li class="list-unstyled">	Stoke-on-Trent	</li>
                        <li class="list-unstyled">	Stuttgart	</li>
                        <li class="list-unstyled">	Sunderland	</li>
                        <li class="list-unstyled">	Surat	</li>
                        <li class="list-unstyled">	Swansea	</li>
                        <li class="list-unstyled">	Swindon	</li>
                        <li class="list-unstyled">	Sydney	</li>
                        <li class="list-unstyled">	Taipei	</li>
                        <li class="list-unstyled">	Tehrān	</li>
                        <li class="list-unstyled">	The Hague	</li>
                        <li class="list-unstyled">	Tianjin	</li>
                        <li class="list-unstyled">	Tokyo	</li>
                        <li class="list-unstyled">	Torino	</li>
                        <li class="list-unstyled">	Toronto	</li>
                        <li class="list-unstyled">	Toulouse	</li>
                        <li class="list-unstyled">	Truro	</li>
                        <li class="list-unstyled">	Tucson	</li>
                        <li class="list-unstyled">	Vancouver	</li>
                        <li class="list-unstyled">	Venice	</li>
                        <li class="list-unstyled">	Vienna	</li>
                        <li class="list-unstyled">	Virginia Beach	</li>
                        <li class="list-unstyled">	Wakefield	</li>
                        <li class="list-unstyled">	Warsaw	</li>
                        <li class="list-unstyled">	Washington DC	</li>
                        <li class="list-unstyled">	Wellington	</li>
                        <li class="list-unstyled">	Wichita	</li>
                        <li class="list-unstyled">	Wilmington	</li>
                        <li class="list-unstyled">	Windhoek	</li>
                        <li class="list-unstyled">	Wolverhampton	</li>
                        <li class="list-unstyled">	Wuhan	</li>
                        <li class="list-unstyled">	Yangon	</li>
                        <li class="list-unstyled">	Yokohama	</li>
                        <li class="list-unstyled">	York	</li>
                        <li class="list-unstyled">	Zagreb	</li>
                        <li class="list-unstyled">	Zurich	</li>
                    </ul>
                </div>
            </div>
        </div>
    </aside>
);

export default Ciudades;